---
- name: Establish IPsec Tunnel
  hosts: onprem-site
  tasks:
    #
    #   TUNNEL 1 CREATION
    #
    - name: Configure IKEv2 Peer - Tunnel 1
      with_items: "{{ t1_ike_peer }}"
      vars:
        ike_peer: "{{ t1_ike_peer }}"
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
          src: "ikev2_peer.j2"

    - name: Configure IKEv2 Proposal - Tunnel 1
      vars:
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
          src: "ikev2_proposal.j2"

    - name: Configure IKEv2 Policy - Tunnel 1
      vars:
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
        src: "ikev2_policy.j2"

    - name: Configure IKEv2 Peer Profile - Tunnel 1
      with_items: "{{ t1_ike_peer_profile }}"
      vars:
        ike_peer_profile: "{{ t1_ike_peer_profile }}"
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
        src: "ikev2_peer_profile.j2"

    - name: Configure Transform Set - Tunnel 1
      with_items: "{{ t1_transform_set }}"
      vars:
        transform_set: "{{ t1_transform_set }}"
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
        src: "transform_set.j2"

    - name: Configure IPsec Profile - Tunnel 1
      vars:
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
        src: "ipsec_profile.j2"

    # - name: Configure interface for tunnel - Tunnel 1
    #   with_items: "{{ t1_interface }}"
    #   vars:
    #     interface: "{{ t1_interface }}"
    #   ios_config:
    #     src: "interface.j2"

    - name: Configure tunnel - Tunnel 1
      with_items: "{{ t1_tunnel }}"
      vars:
        tunnel: "{{ t1_tunnel }}"
        tunnel_name: "{{tunnel1_name}}"
      ios_config:
        src: "tunnel.j2"
    #
    #   TUNNEL 2 CREATION
    #

    - name: Configure IKEv2 Peer - Tunnel 2
      with_items: "{{ t2_ike_peer }}"
      vars:
        ike_peer: "{{ t2_ike_peer }}"
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "ikev2_peer.j2"
    
    - name: Configure IKEv2 Proposal - Tunnel 2
      vars:
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
          src: "ikev2_proposal.j2"

    - name: Configure IKEv2 Policy - Tunnel 2
      vars:
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "ikev2_policy.j2"

    - name: Configure IKEv2 Peer Profile - Tunnel 2
      with_items: "{{ t2_ike_peer_profile }}"
      vars:
        ike_peer_profile: "{{ t2_ike_peer_profile }}"
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "ikev2_peer_profile.j2"

    - name: Configure Transform Set - Tunnel 2
      with_items: "{{ t2_transform_set }}"
      vars:
        transform_set: "{{ t2_transform_set }}"
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "transform_set.j2"

    - name: Configure IPsec Profile - Tunnel 2
      vars:
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "ipsec_profile.j2"

    # - name: Configure interface for tunnel
    #   with_items: "{{ t2_interface }}"
    #   vars:
    #     interface: "{{ t2_interface }}"
    #   ios_config:
    #     src: "interface.j2"

    - name: Configure tunnel - Tunnel 2
      with_items: "{{ t2_tunnel }}"
      vars:
        tunnel: "{{ t2_tunnel }}"
        tunnel_name: "{{tunnel2_name}}"
      ios_config:
        src: "tunnel.j2"
